---
# tasks file for ansible_role_install_grafana


- name: Install packages 
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - adduser
    - libfontconfig1
    - musl

- name: Install a .deb package from the internet
  become: true
  ansible.builtin.apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.2.0_amd64.deb


- name: Create 'datasources.yml'
  become: true
  ansible.builtin.template:
    src: "datasources.j2"
    dest: "/etc/grafana/provisioning/datasources/datasources.yaml"


    #- name: Create dashboard
    #  become: true
    #  ansible.builtin.copy:
    #    src: "node_exporter_dashboard.yml"
    #    dest: "/etc/grafana/provisioning/dashboards/node_exporter.yaml"


- name: Enable service 'grafana-server' and ensure it is started
  become: true
  ansible.builtin.systemd:
    name: grafana-server
    enabled: true
    state: started

